VULN-1098081 upgrading jetty-http and release config
atlassian-forks/ehcache2 pull request #3
Opened 2024-02-03 05:58 UTC by ajaysharma2

https://asecurityteam.atlassian.net/browse/VULN-1098081?filter=13156
Upgrading jetty-htty to use  10.0.16
Changed repository distribution management pointing to atlassian-3rd-party
Changed SCM tag
Updated below deps
thirdparty-bom to 4.4.0.5.17
management-core.version 4.4.0.3.31
system-tests-parent 4.4.0.5.17

2024-02-08 04:00 UTC, rjatkins requested changes
Do we even need to keep the terracotta management code in here? We don't use any of it in Confluence, as we're using Hazelcast for cluster caching instead

2024-02-08 04:00 UTC, rjatkins commented on pom.xml
> +    <jetty.version>10.0.16</jetty.version>
Jetty 10.0.20 is out. We should be using that

2024-02-08 04:00 UTC, rjatkins commented on pom.xml
> +      </dependency>
Instead of direct dependencyManagement here, we should be using jetty-bom:
```
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-bom</artifactId>
    <version>10.0.20</version>
    <type>pom</type>
</dependency>
```

2024-02-08 11:44 UTC, ajaysharma2 commented
> Do we even need to keep the terracotta management code in here? We don't use any of it in Confluence, as we're using Hazelcast for cluster caching instead

This is being used in below modules
management-ehcache-v1
management-ehcache-v2

Let me check if i can remove this module from it

2024-02-08 13:02 UTC, ajaysharma2 commented
Branch [2.11.1-atlassian-x](https://github.com/atlassian-forks/ehcache2/tree/2.11.1-atlassian-x) is using jdk 11

2024-02-09 02:51 UTC, rjatkins approved these changes

2024-02-09 09:45 UTC, rjatkins approved these changes

2024-02-11 23:47 UTC, Ganeshgautam approved these changes

2024-02-13 12:09 UTC, merged